// <auto-generated />
using System;
using ALE.TimeRegistration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ALE.TimeRegistration.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201225185306_AddUsers")]
    partial class AddUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.AppTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("WorkTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TaskId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8554266-b401-4519-9aeb-a9283053fc58",
                            Email = "aboynamedsue@JCash.com",
                            EmailConfirmed = true,
                            LastName = "Cash",
                            LockoutEnabled = false,
                            Name = "Johnny",
                            NormalizedEmail = "ABOYNAMEDSUE@JCASH.COM",
                            NormalizedUserName = "ABOYNAMEDSUE@JCASH.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEE/zh8ThYTRv5brW0vvFJuiJumu06jkqM56nmlYyfiCCZlELXGLJRSUeipp5HQ3zlA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "VVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "aboynamedsue@JCash.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea936088-7c16-4dae-8679-ccb63b4b6529",
                            Email = "EchtElkeKant@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Kant",
                            LockoutEnabled = false,
                            Name = "Elke",
                            NormalizedEmail = "ECHTELKEKANT@HOTMAIL.COM",
                            NormalizedUserName = "ECHTELKEKANT@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEC4RqwbaUa2y11zbotKbN91j9INtaeYY2NYYJj/W3FySSya2wgyBIVH5UzSvnligXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "LPRQIVUHQZ9B9VK0RQPN9LLR2JUDMOKX",
                            TwoFactorEnabled = false,
                            UserName = "EchtElkeKant@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87512ca8-3082-41c9-a799-125a1724dfdb",
                            Email = "Ialwayswin@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Pot",
                            LockoutEnabled = false,
                            Name = "Jack",
                            NormalizedEmail = "IALWAYSWIN@GMAIL.COM",
                            NormalizedUserName = "IALWAYSWIN@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAELtnhq0xAPjHlTVUK7gfNWBBeticpTfa0OIZIaY68qIYC+ia9n1SFIaBS+qcoaIE8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "CGZLWFPLDP93ZCFWTQ19E9LGZAH3EDV4",
                            TwoFactorEnabled = false,
                            UserName = "Ialwayswin@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a9bb722-0187-44d6-ab37-35bd39a46abd",
                            Email = "ErnaVanvoren@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Vanvoren",
                            LockoutEnabled = false,
                            Name = "Erna",
                            NormalizedEmail = "ERNAVANVOREN@HOTMAIL.COM",
                            NormalizedUserName = "ERNAVANVOREN@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEN6bckEB+sr0+nk6sl9f6mRkkZH06VhtrUP5BccmBq/O+bjTGhEt/muUau0wmSNnXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "KEVV7QQDZVPGXW0LIRHWRUBJDWV1BEOK",
                            TwoFactorEnabled = false,
                            UserName = "ErnaVanvoren@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2fa68a7a-8187-440a-92d3-9332f602a90c",
                            Email = "RogerDoeniemee@telenet.be",
                            EmailConfirmed = true,
                            LastName = "Vangenechte",
                            LockoutEnabled = false,
                            Name = "Roger",
                            NormalizedEmail = "ROGERDOENIEMEE@TELENET.BE",
                            NormalizedUserName = "ROGERDOENIEMEE@TELENET.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAECwpXgPz2azBfqeIRxDIVqkGDEtGx5Ygxk6+Ko5NaJo+HXVJsZ04CKPbj9HKeS8AYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DMQ1MNFMDVWEMHCWA4TOPXZUCR97WIGJ",
                            TwoFactorEnabled = false,
                            UserName = "RogerDoeniemee@telenet.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000006",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6089fee-e038-4e51-a688-efd386d13801",
                            Email = "CharlesDurue@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Verstraete",
                            LockoutEnabled = false,
                            Name = "Karel",
                            NormalizedEmail = "CHARLESDURUE@HOTMAIL.COM",
                            NormalizedUserName = "CHARLESDURUE@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEKUbDlK7+IUmdoYo7SlhoZhEgAwYa6XUr5C0CF72kswsPunNa1IrGVtM43RjPC7zmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "GOHAS6DGS3TEFB8CKVA1O0YY7L7QOJGY",
                            TwoFactorEnabled = false,
                            UserName = "CharlesDurue@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000007",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b61bb5e0-6249-4017-8f66-c2e793cead19",
                            Email = "katringring@skynet.be",
                            EmailConfirmed = true,
                            LastName = "Vanbelleghem",
                            LockoutEnabled = false,
                            Name = "Katleen",
                            NormalizedEmail = "KATRINGRING@SKYNET.BE",
                            NormalizedUserName = "KATRINGRING@SKYNET.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEPt1COmtB8aZqMqV571p1U+kSd+FgnWpuXAlv/9o2aK2XYzwf/wQ58Bnnq5XARR/4w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "TX2YKCJILNPIIAS7Y4XDXNU7ATXAMEXW",
                            TwoFactorEnabled = false,
                            UserName = "katringring@skynet.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000008",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71225b1c-93a9-4e98-9769-e2bac0cf8c81",
                            Email = "SnelnEddy@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Guapo",
                            LockoutEnabled = false,
                            Name = "Edwardo",
                            NormalizedEmail = "SNELNEDDY@HOTMAIL.COM",
                            NormalizedUserName = "SNELNEDDY@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEPJWH5e5MpPdTcTG3jrPL1axo9K0nRNQZVGOnfTEyYQ8Wvp6elJ94SakSQIvATpKAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "AY8SBXVKA6Z6MXJXBYIIE9JIAOQV2DJO",
                            TwoFactorEnabled = false,
                            UserName = "SnelnEddy@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000009",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00b46ecb-768e-4d9e-8168-c947145342aa",
                            Email = "Andy123@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Degught",
                            LockoutEnabled = false,
                            Name = "Andy",
                            NormalizedEmail = "ANDY123@GMAIL.COM",
                            NormalizedUserName = "ANDY123@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAELcRawJt6K49B4uA2nc+KesuiOsniRhgCVLBMT8U+/MGOlKXiwooWzigFNfmhJeTmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "AERAYD2O3KEIAGCLLIP7O8QNVSXU8PUD",
                            TwoFactorEnabled = false,
                            UserName = "Andy123@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000010",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6d41496-5440-4fb4-b12b-b36a66bd271c",
                            Email = "IloveyouTomorrow@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Demain",
                            LockoutEnabled = false,
                            Name = "Annie",
                            NormalizedEmail = "ILOVEYOUTOMORROW@HOTMAIL.COM",
                            NormalizedUserName = "ILOVEYOUTOMORROW@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEBI6SCpXg5ltphB5jLnhC+PYDFwOlXDMr7T+U/nEAhNHV8RVJ2ySjm9OAkkxyKgCXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "OJUDGXCPUCPYDMIQTIWMSRTLXH4NMKDB",
                            TwoFactorEnabled = false,
                            UserName = "IloveyouTomorrow@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000011",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a01d31d2-66ce-40a5-9a38-f5a02d65cdae",
                            Email = "Satchel@steelpanther.com",
                            EmailConfirmed = true,
                            LastName = "Parrish",
                            LockoutEnabled = false,
                            Name = "Russ",
                            NormalizedEmail = "SATCHEL@STEELPANTHER.COM",
                            NormalizedUserName = "SATCHEL@STEELPANTHER.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAELRMgmw9FpYDw1qV4ige2gJ7/YbrdGqDf8B0s2F99CO4XLk3QHObivyiFFpF+FfZyw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "W7VNKA17XODMDCKG5JBXZQCLUQSRF32F",
                            TwoFactorEnabled = false,
                            UserName = "Satchel@steelpanther.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000012",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "727ea679-d671-4406-97cf-3a00468fd7e6",
                            Email = "DePijpVanMaarten@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Pijpers",
                            LockoutEnabled = false,
                            Name = "Maarten",
                            NormalizedEmail = "DEPIJPVANMAARTEN@GMAIL.COM",
                            NormalizedUserName = "DEPIJPVANMAARTEN@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEL43r5GkPyQcH54RZqNGI5IgeYK2gu//iO5nEQ5X80yTL360pE7OTRPT1MFv4jXLFw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NZVCLM9FJXG84V7AAF3WNV9UX88PSSAD",
                            TwoFactorEnabled = false,
                            UserName = "DePijpVanMaarten@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000013",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "979b7fae-dee1-443f-89cd-cd5d7e075296",
                            Email = "EdwardLeCanard@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Vaneende",
                            LockoutEnabled = false,
                            Name = "Edward",
                            NormalizedEmail = "EDWARDLECANARD@HOTMAIL.COM",
                            NormalizedUserName = "EDWARDLECANARD@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEMu1JDOu4oKrdGkRTX+FX+CDSNuknw/dZR312s3bPvRpN/cnfAdz9eRV8q9VOTIg1w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "X50KHZXPUONAXCIOYAP1VN2KWJNQF8YF",
                            TwoFactorEnabled = false,
                            UserName = "EdwardLeCanard@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000014",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3205df9b-0609-478c-953a-3ebc1cbd3894",
                            Email = "DeYoeri@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Declerk",
                            LockoutEnabled = false,
                            Name = "Yoeri",
                            NormalizedEmail = "DEYOERI@GMAIL.COM",
                            NormalizedUserName = "DEYOERI@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEN6PxONlTF9oF+iiz6L4W23jEr+twtnbZtDIt+Icsls3olG4ZOgd6fRk2/dG9gO+7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E9HTNSBN303BXB434HYORNEMWKFR9F0K",
                            TwoFactorEnabled = false,
                            UserName = "DeYoeri@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000015",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7d20267-f0ca-40b8-b5a9-82c6e1bbf7b6",
                            Email = "CalmingCamille@telenet.be",
                            EmailConfirmed = true,
                            LastName = "Thee",
                            LockoutEnabled = false,
                            Name = "Camille",
                            NormalizedEmail = "CALMINGCAMILLE@TELENET.BE",
                            NormalizedUserName = "CALMINGCAMILLE@TELENET.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEGNm2TLWsK3nnMmUpmDrI8e5svUqqJKs/Mi0QIpcGnHOScM/3OxUDfgsCwWHA9i3+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NB8OXAMNMR8SWHOY6ACNDYQE4VAGFEEP",
                            TwoFactorEnabled = false,
                            UserName = "CalmingCamille@telenet.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000016",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59cfeb05-2937-4806-8f27-accbc1ccfe91",
                            Email = "Thebestginger@qotsa.com",
                            EmailConfirmed = true,
                            LastName = "Homme",
                            LockoutEnabled = false,
                            Name = "Josh",
                            NormalizedEmail = "THEBESTGINGER@QOTSA.COM",
                            NormalizedUserName = "THEBESTGINGER@QOTSA.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEGKO2R1hpEbhAUk7CQRyrHs33r/BpZwoVbeDs2/sRKnmx4OUVOtYMheUQW5h+Ssy3g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ZUYKIDLJWUZXNXN6BK6Z6QCZO5WXOYNR",
                            TwoFactorEnabled = false,
                            UserName = "Thebestginger@qotsa.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000017",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68e80c7b-4679-4fc7-8f8a-7dfcf165d726",
                            Email = "Zwaffelaere@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Uytebroeck",
                            LockoutEnabled = false,
                            Name = "Piet",
                            NormalizedEmail = "ZWAFFELAERE@GMAIL.COM",
                            NormalizedUserName = "ZWAFFELAERE@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEDW9XgLVIgOO7WzkG6A7TgP0yWDQDtTcx12/31bVwbU2bIs4144E1WCLqEivvs5zXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "HGIXXQPIK4FFBOOUNMFY7GN6GDHXEVV1",
                            TwoFactorEnabled = false,
                            UserName = "Zwaffelaere@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000018",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1000963-395c-4507-83df-8f4b9e784db1",
                            Email = "SterkeJan33@pandora.be",
                            EmailConfirmed = true,
                            LastName = "Lefort",
                            LockoutEnabled = false,
                            Name = "Jan",
                            NormalizedEmail = "STERKEJAN33@PANDORA.BE",
                            NormalizedUserName = "STERKEJAN33@PANDORA.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEGhN/2QHCsaOt7GSsDKIDDw97g78I/nGbMlJMHQTm0PXBTygAnqp6MvjtOoZ19vTXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "WGY5YWIB4XK6LUI2TBROBMXVLQKNNWOV",
                            TwoFactorEnabled = false,
                            UserName = "SterkeJan33@pandora.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000019",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b9e1dbac-e651-482a-98a4-8e24583f29c0",
                            Email = "RietjeGessof@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Gessof",
                            LockoutEnabled = false,
                            Name = "Rita",
                            NormalizedEmail = "RIETJEGESSOF@HOTMAIL.COM",
                            NormalizedUserName = "RIETJEGESSOF@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEDSuydX6YapKJk1/8WagypIt/xLOFZYYJdDKRnvA021IZzUctfLBcFqxl6CmfYmnBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9H2QG7IPOUORADDNMF2ISIRSOGZJNXGZ",
                            TwoFactorEnabled = false,
                            UserName = "RietjeGessof@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000020",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86d42357-8dbc-48c9-886d-3a1b957f2075",
                            Email = "willywilly@thescabs.be",
                            EmailConfirmed = true,
                            LastName = "Lambregt",
                            LockoutEnabled = false,
                            Name = "Willy",
                            NormalizedEmail = "WILLYWILLY@THESCABS.BE",
                            NormalizedUserName = "WILLYWILLY@THESCABS.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEO2h+/svyq64E6PaXqGZ+bPjyCftqHT7S4I7vnwegZClCUTALoTqJHfL/AxdoqMLXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7F7LSOHNMOKGFGQVMMGOX3SHM3PBNHQB",
                            TwoFactorEnabled = false,
                            UserName = "willywilly@thescabs.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000021",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d7280862-2341-462a-8fb5-1380edea1422",
                            Email = "PescadoLover@skynet.be",
                            EmailConfirmed = true,
                            LastName = "Vervis",
                            LockoutEnabled = false,
                            Name = "Kelly",
                            NormalizedEmail = "PESCADOLOVER@SKYNET.BE",
                            NormalizedUserName = "PESCADOLOVER@SKYNET.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEFoQiv89L4IMGVAqUm3NCe30KCVyQz+mZWWc+3g0HI8b0PRRlIT6mw+6xecmI3iUQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "WGLZXEZUI3NLP8ZWUYK5CFN8XWBT7ATX",
                            TwoFactorEnabled = false,
                            UserName = "PescadoLover@skynet.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000022",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0fc3e5d4-f6ce-4160-aa94-d2acc0be114d",
                            Email = "TomVanmarcke@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Vantomme",
                            LockoutEnabled = false,
                            Name = "Marc",
                            NormalizedEmail = "TOMVANMARCKE@GMAIL.COM",
                            NormalizedUserName = "TOMVANMARCKE@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEEUaZYCjqqvb87gaqZqG/6hvL+BinqCOF+cPKx/I+mvIEUXvMgzYILSKmPvjUsuM2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "OIKDBFPAR5GJKJ91OUAOXNKR1CMLSTFC",
                            TwoFactorEnabled = false,
                            UserName = "TomVanmarcke@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000023",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f42511c-f74f-442c-a8f2-28b10d2bc114",
                            Email = "Loewiloewie@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Decruy",
                            LockoutEnabled = false,
                            Name = "Louis",
                            NormalizedEmail = "LOEWILOEWIE@HOTMAIL.COM",
                            NormalizedUserName = "LOEWILOEWIE@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEKiyo1MTjIGA0VwvBi3kisKkJSsjZo0hZRb3N+t/VW9ikNh8PU6xZvyt67OAL//ilA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "F0SRUYTP4OF6TSFD3CNJBX5ECAJFPPFZ",
                            TwoFactorEnabled = false,
                            UserName = "Loewiloewie@hotmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000024",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b52a849c-4b01-4dda-ac2f-30f6b08fe075",
                            Email = "Giezijtem@skynet.be",
                            EmailConfirmed = true,
                            LastName = "Emnie",
                            LockoutEnabled = false,
                            Name = "Ben",
                            NormalizedEmail = "GIEZIJTEM@SKYNET.BE",
                            NormalizedUserName = "GIEZIJTEM@SKYNET.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAECH+m8I8KMFPi2IjxiSnyx8fZvDt0VNul+aoixdPiPhRPQ3Sc5p1ZWIeO0bWe0qNIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "PHLIIUHLZLGB2UTDD2LHUFROZ7TDQAD7",
                            TwoFactorEnabled = false,
                            UserName = "Giezijtem@skynet.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000025",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "018aba24-a96f-44e9-a058-a047d0bd0b53",
                            Email = "ConnieBeter@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Moeleker",
                            LockoutEnabled = false,
                            Name = "Connie",
                            NormalizedEmail = "CONNIEBETER@GMAIL.COM",
                            NormalizedUserName = "CONNIEBETER@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEKZLKpoa0UOm3zOZNtoNiAlFLm/DfnSFLNwlVGKJ3T8EbKJswDBlISDGfaPj4YgIng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "FWM36IDUG00055IF56RZWA2CR9OYCVB3",
                            TwoFactorEnabled = false,
                            UserName = "ConnieBeter@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000026",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc117b43-d867-4f86-8ac4-8d4efc2820c4",
                            Email = "GezondePeter@telenet.be",
                            EmailConfirmed = true,
                            LastName = "Celie",
                            LockoutEnabled = false,
                            Name = "Peter",
                            NormalizedEmail = "GEZONDEPETER@TELENET.BE",
                            NormalizedUserName = "GEZONDEPETER@TELENET.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAENcIS7Bxp8FRjru7eYmge6e2kascpAx0MRr7Br6TUExuY/4qfBjP1srKBaa2sJhvdg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "TJLKW00301EENWVWL2MCPLTCU18IT7XY",
                            TwoFactorEnabled = false,
                            UserName = "GezondePeter@telenet.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000027",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1993d307-e257-4e29-8487-b230037199aa",
                            Email = "Bennernie@skynet.be",
                            EmailConfirmed = true,
                            LastName = "Thuys",
                            LockoutEnabled = false,
                            Name = "Benny",
                            NormalizedEmail = "BENNERNIE@SKYNET.BE",
                            NormalizedUserName = "BENNERNIE@SKYNET.BE",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEKkL6y4DvSrptMEd51RhUWWcN+a/Dw1w0AYgx3QM18h90l03ZWGYKeNuyQNqK0PJdg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "KXW8TS8VIEG0BL1OIA7U2PASSALDXMV3",
                            TwoFactorEnabled = false,
                            UserName = "Bennernie@skynet.be"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000028",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b017e971-0a03-4aa0-86e5-b3d1c603d64b",
                            Email = "Thebestbusker@london.com",
                            EmailConfirmed = true,
                            LastName = "Cole",
                            LockoutEnabled = false,
                            Name = "Cam",
                            NormalizedEmail = "THEBESTBUSKER@LONDON.COM",
                            NormalizedUserName = "THEBESTBUSKER@LONDON.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAENPIRKxyuNU2grH4C07Sd1Cw43Dvxd2pKFQbEKvMG/fKlHQgF5VYGMgdSEL/RQp7EA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "VRVLNRMUMHA6IADTQ7CO9VCIMVX4OMO5",
                            TwoFactorEnabled = false,
                            UserName = "Thebestbusker@london.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000029",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50d8c368-d7f1-4e3f-8216-6ba5c5e3e76a",
                            Email = "CoronaTopper@gmail.com",
                            EmailConfirmed = true,
                            LastName = "Root",
                            LockoutEnabled = false,
                            Name = "Claude",
                            NormalizedEmail = "CORONATOPPER@GMAIL.COM",
                            NormalizedUserName = "CORONATOPPER@GMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEFfG1lX4Pbhpd3k8TukVQJSBSlzZLAjv0gFo7dMKnG529oCNjiDz6rZP1jfArdC3uQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "W7IEDSQT3GEVZWUOTXG8CL1PI3K6MXU7",
                            TwoFactorEnabled = false,
                            UserName = "CoronaTopper@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000030",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55690745-3bfd-43ad-abbe-af37f549182c",
                            Email = "rapgewoon@hotmail.com",
                            EmailConfirmed = true,
                            LastName = "Wenne",
                            LockoutEnabled = false,
                            Name = "Eve",
                            NormalizedEmail = "RAPGEWOON@HOTMAIL.COM",
                            NormalizedUserName = "RAPGEWOON@HOTMAIL.COM",
                            Password = "TimeReg2020",
                            PasswordHash = "AQAAAAEAACcQAAAAEMIU4gzVaGUlZ1J6tOHTGM4kCCDREbF7JbnQ3w1ZmZYQpzu5RHu3Nr+5ubYsIYj0dw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "JF6GSUYRRSWNWXY9Z1HUJLK1GUQREXOO",
                            TwoFactorEnabled = false,
                            UserName = "rapgewoon@hotmail.com"
                        });
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("WorkDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("WorkTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            ConcurrencyStamp = "211459f2-edec-4c10-b876-db6d89bca2f7",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000001",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.AppTask", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Message", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", "Sender")
                        .WithMany("SendMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ALE.TimeRegistration.Core.Entities.AppTask", "Task")
                        .WithMany("Messages")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Picture", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.AppTask", "Task")
                        .WithMany("Pictures")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.UserTask", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.AppTask", "Task")
                        .WithMany("TaskUsers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", "User")
                        .WithMany("UserTasks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
