// <auto-generated />
using System;
using ALE.TimeRegistration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ALE.TimeRegistration.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201111172646_AddUserTaskSeeder")]
    partial class AddUserTaskSeeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TaskId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000100"),
                            Name = "Toyota Motor"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            Name = "Colruyt"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            Name = "Engie Electrabel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            Name = "Janssen Pharmaceutica"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            Name = "Total Belgium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            Name = "BASF Antwerpen"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            Name = "Delhaize De Leeuw"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            Name = "Volvo Car Belgium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            Name = "ArcelorMittal Belgium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            Name = "Mastercard Europe"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000110"),
                            Name = "Proximus"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000111"),
                            Name = "AXA Belgium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000112"),
                            Name = "Allianz Benelux"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000113"),
                            Name = "Daikin Europe"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000114"),
                            Name = "bpost"
                        });
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("WorkTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "aboynamedsue@JCash.com",
                            LastName = "Cash",
                            Name = "Johnny",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Email = "EchtElkeKant@hotmail.com",
                            LastName = "Kant",
                            Name = "Elke",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Email = "Ialwayswin@gmail.com",
                            LastName = "Pot",
                            Name = "Jack",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Email = "ErnaVanvoren@hotmail.com",
                            LastName = "Vanvoren",
                            Name = "Erna",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Email = "RogerDoeniemee@telenet.be",
                            LastName = "Vangenechte",
                            Name = "Roger",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Email = "CharlesDurue@hotmail.com",
                            LastName = "Verstraete",
                            Name = "Karel",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Email = "Katringring@skynet.be",
                            LastName = "Vanbelleghem",
                            Name = "Katleen",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Email = "SnelnEddy@hotmail.com",
                            LastName = "Guapo",
                            Name = "Edwardo",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Email = "Andy123@gmail.com",
                            LastName = "Degught",
                            Name = "Andy",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Email = "IloveyouTomorrow@hotmail.com",
                            LastName = "Demain",
                            Name = "Annie",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Email = "Satchel@steelpanther.com",
                            LastName = "Parrish",
                            Name = "Russ",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Email = "DePijpVanMaarten@gmail.com",
                            LastName = "Pijpers",
                            Name = "Maarten",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Email = "EdwardLeCanard@hotmail.com",
                            LastName = "Vaneende",
                            Name = "Edward",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Email = "DeYoeri@gmail.com",
                            LastName = "Declerk",
                            Name = "Yoeri",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Email = "CalmingCamille@telenet.be",
                            LastName = "Thee",
                            Name = "Camille",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Email = "Thebestginger@qotsa.com",
                            LastName = "Homme",
                            Name = "Josh",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Email = "Zwaffelaere@gmail.com",
                            LastName = "Uytebroeck",
                            Name = "Piet",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Email = "SterkeJan33@pandora.be",
                            LastName = "Lefort",
                            Name = "Jan",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Email = "RietjeGessof@hotmail.com",
                            LastName = "Gessof",
                            Name = "Rita",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Email = "willywilly@thescabs.be",
                            LastName = "Lambregt",
                            Name = "Willy",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Email = "PescadoLover@skynet.be",
                            LastName = "Vervis",
                            Name = "Kelly",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Email = "TomVanmarcke@gmail.com",
                            LastName = "Vantomme",
                            Name = "Marc",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Email = "Loewiloewie@hotmail.com",
                            LastName = "Decruy",
                            Name = "Louis",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Email = "Giezijtem@skynet.be",
                            LastName = "Emnie",
                            Name = "Ben",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Email = "ConnieBeter@gmail.com",
                            LastName = "Moeleker",
                            Name = "Connie",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Email = "GezondePeter@telenet.be",
                            LastName = "Celie",
                            Name = "Peter",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Email = "Bennernie@skynet.be",
                            LastName = "Thuys",
                            Name = "Benny",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Email = "Thebestbusker@london.com",
                            LastName = "Cole",
                            Name = "Cam",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Email = "CoronaTopper@gmail.com",
                            LastName = "Root",
                            Name = "Claude",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Email = "rapgewoon@hotmail.com",
                            LastName = "Wenne",
                            Name = "Eve",
                            Password = "TimeReg2020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000200")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000205")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000206")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000207")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000208")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000209")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000210")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000211")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000212")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000213")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000214")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000215")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000216")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000217")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000218")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000219")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000220")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000221")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000222")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000223")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000224")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000225")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000226")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000227")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000228")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000229")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000230")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000231")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000232")
                        });
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.UserTask", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000200")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000007"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000205")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000010"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000206")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000011"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000207")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000011"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000208")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000011"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000209")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000210")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000016"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000211")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000017"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000212")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000020"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000213")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000020"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000214")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000021"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000215")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000021"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000216")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000021"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000217")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000022"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000218")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000023"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000219")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000024"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000220")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000024"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000221")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000025"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000223")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000017"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000224")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000025"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000225")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000026"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000226")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000027"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000227")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000028"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000228")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000029"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000229")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000030"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000230")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000015"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000231")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000030"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000232")
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000030"),
                            TaskId = new Guid("00000000-0000-0000-0000-000000000233")
                        });
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Message", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", "Sender")
                        .WithMany("SendMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ALE.TimeRegistration.Core.Entities.Task", "Task")
                        .WithMany("Messages")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Picture", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.Task", "Task")
                        .WithMany("Pictures")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.Task", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ALE.TimeRegistration.Core.Entities.UserTask", b =>
                {
                    b.HasOne("ALE.TimeRegistration.Core.Entities.Task", "Task")
                        .WithMany("TaskUsers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ALE.TimeRegistration.Core.Entities.User", "User")
                        .WithMany("UserTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
